### ISSUE TITLE
Support custom buildings/containers

### ISSUE THREAD

**Issue by fossifus** [bitwisejon/StardewValleyMods#19]
Hi Jon, was just trying to get your mod to play nicely with a custom Solid Foundations building and wound up here in your source code. Saw your comment in ModEntry.cs dated a week ago, you're already a step ahead of me. But figured I'd make an issue anyway for visibility. Thanks for your hard work!

**Comment by bitwisejon** [comment]
Hello! This (limited) support is added in the 4.0.0 update going out today to support Stardew Valley 1.6!
